

<div class="content mnu-etalase">
	<div class="brandbox" onclick="javascript:$ui.opencatalog('eag')">Aigner</div>	
	<div class="brandbox" onclick="javascript:$ui.opencatalog('hbs')">Hugo Boss</div>	
	<div class="brandbox" onclick="javascript:$ui.opencatalog('frg')">Ferragamo</div>	
	<div class="brandbox" onclick="javascript:$ui.opencatalog('gex')">Geox</div>	
	<div class="brandbox" onclick="javascript:$ui.opencatalog('fla')">Furla</div>	
	<div class="brandbox" onclick="javascript:$ui.opencatalog('fkp')">Find Kapoor</div>	
	<div class="brandbox" onclick="javascript:$ui.opencatalog('tod')">Tods</div>	
	<div class="brandbox" onclick="javascript:$ui.opencatalog('can')">Canali</div>	
</div>




